### ISSUE TITLE
Find a replacement for TSLint

### ISSUE THREAD

**Issue by jonkoops** [react-dropzone/file-selector#101]
We're still using TSLint [which has been deprecated](https://blog.palantir.com/tslint-in-2019-1a144c2317a9) for some time now. Ideally we move to a different stack for linting. The most mature option is [`typescript-eslint`](https://typescript-eslint.io/), which is recommended as the official replacement of TSLint. It does carry a lot of dependencies and needs ESLint to function.

Alternatively, there has been a lot of development around [OXC](https://oxc.rs/) (JavaScript Oxidation Compiler), specifically [`oxclint`](https://oxc.rs/docs/guide/usage/linter). This linter is a lot less mature but carries no dependencies and is extremely fast due to it being a native binary, but also lacks all the features such as type-aware linting.

@rolandjitsu I think for now we should probably go for the ESLint + `typescript-eslint` combo, even if it is a bit more maintenance. WDYT?

**Comment by rolandjitsu** [comment]
@jonkoops I think that's the sensible thing to do. ESLint w/ typescript support is probably the way to go. And use the `eslint-plugin-prettier/recommended`, should be good enough.

**Comment by jonkoops** [comment]
Great! Then I will try and set something up.

**Comment by jonkoops** [comment]
This has been resolved under #102
