### ISSUE TITLE
[BUG] Cannot read properties of undefined (reading 'getFile')

### ISSUE THREAD

**Issue by MathiasWP** [react-dropzone/file-selector#120]
**Describe the bug**
To be honest, i am not quite sure how this has happened. Sentry captured this, and we're left wondering how this is possible. Any help would be much appreciated.

**Expected behavior**
This should not throw.

**Screenshots**
<img width="1479" alt="image" src="https://github.com/user-attachments/assets/5e126d16-f231-416a-a895-a933b369d407">

**Desktop (please complete the following information):**
 - OS: Windows >= 10
 - Browser: Edge
 - Version: 131.0.0

**Additional context**
Let me know if there's anything i can do to help investigate this further.

**Comment by jonkoops** [comment]
This seems like it would be fixed by #114

**Comment by MathiasWP** [comment]
> This seems like it would be fixed by #114

Looks like it! Looking at the [API](https://developer.mozilla.org/en-US/docs/Web/API/DataTransferItem/getAsFileSystemHandle) is seems like the `entry.kind === "file"` would help here.

**Comment by rolandjitsu** [comment]
@jonkoops the same fix is in https://github.com/react-dropzone/file-selector/pull/107, though, it would reject there. Alternatively, as suggested in some of the comments there, in case the handle is undefined, we can continue to the `getAsFile`. I can rebase it and make it ready for master.

Following up on that conversation, the type is file at that point, so I'm also wondering why it is undefined.

**Comment by jonkoops** [comment]
> Following up on that conversation, the type is file at that point, so I'm also wondering why it is undefined.

Indeed, it is hard to imagine a circumstance where it would be.
