### ISSUE TITLE
Font file types

### ISSUE THREAD

**Issue by smcgov1** [react-dropzone/file-selector#21]
I'm having issues uploading font files with the extensions `.EOG` and `.TTF` to React-dropzone. I know these fonts do not have Mime types attached to them. Do you know a way I can get around this? 

https://github.com/react-dropzone/react-dropzone/issues?q=is%3Aissue+is%3Aclosed

**Comment by rolandjitsu** [comment]
@smcgov1 just don't add the `{accept}` prop, that should do it.

**Comment by rolandjitsu** [comment]
Gonna close this now.
