### ISSUE TITLE
should `getInputFiles` filter out the ignoredFiles?

### ISSUE THREAD

**Issue by coldpour** [react-dropzone/file-selector#24]
https://github.com/react-dropzone/file-selector/blob/master/src/file-selector.ts#L33

I notice that the drag events filter out the ignored files, but the file input event does not, why is that?

**Comment by rolandjitsu** [comment]
Input files are files that you select using the native browser file select and the ignored files are not going to show up (dot files on unix systems are usually hidden and the thumbs file on Windows is also a hidden file).

Have you found some issues with this?

**Comment by coldpour** [comment]
Ah you’re right, that’s true for just files. However when uploading a
folder using the webkitdirectory attribute, it seems to grab the .DS_Store
which always ends up in the rejectedFiles list.

**Comment by rolandjitsu** [comment]
If it causes issues for you, please feel free to make a PR and add that file to the ignored files list + use the filter fn on the input event as well.

**Comment by rolandjitsu** [comment]
Gonna close this for now. Please make a PR if this is something you still want.
