### ISSUE TITLE
mime-type empty in react-dropzone

### ISSUE THREAD

**Issue by kris2kris** [react-dropzone/file-selector#25]
Hello,

I have a react dropzone with accept condition on Excel file but sometimes MIME-type is empty and all files are rejected. (The problem seems to be random)
Do you think it is possible to use something like https://github.com/jshttp/mime-types or https://github.com/jshttp/mime-db to determine the MIME type of the files and avoid these problems of rejected files ?

PS : The fastest solution would be to add it in COMMON_MIME_TYPES but maybe using mime-db instead of COMMON_MIME_TYPES is better to do it only once.

Thank you

**Comment by rolandjitsu** [comment]
I'm not sure that we can fix this easily. I think this is a known issue with some browsers not reporting the proper mime type. Check https://github.com/react-dropzone/react-dropzone/issues/276#issuecomment-308637324.

You're welcome to make a PR and try to make use of one of those libs, but keep in mind that we don't want it to be bundled with the rest of the code and there should also be a way to not the lib.
