### ISSUE TITLE
React Dropzone does not detect or trigger any event when the file to be dropped is selected from a zip

### ISSUE THREAD

**Issue by akshaybheda** [react-dropzone/file-selector#26]
I am using React Dropzone, When i try to drag and drop a file from zip file to the dropzone, It does not trigger any event nor does it get's detected.

**Comment by rolandjitsu** [comment]
I'm not sure this issue is related to this lib. And when you say `When i try to drag and drop a file from zip file to the dropzone` do you mean you're drag 'n' dropping a zip file? Or are you using some unzipping tool and trying to drag and drop a file from there to the dropzone?
