### ISSUE TITLE
Include LICENSE file in distribution

### ISSUE THREAD

**Issue by RobertBorg** [react-dropzone/file-selector#35]
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
No LICENSE file is included in distribution
**If the current behavior is a bug, please provide the steps to reproduce.**

1.
2.
3.

**What is the expected behavior?**
I expect LICENSE file to be included in distribution
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Other info**

**Comment by rolandjitsu** [comment]
Closed with [v0.2.2](https://github.com/react-dropzone/file-selector/releases/tag/v0.2.2).
