### ISSUE TITLE
Webpack build fails with 0.1.16

### ISSUE THREAD

**Issue by danrot** [react-dropzone/file-selector#37]
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**

My webpack build is failing with the following error message when using the latest 0.1 version of `file-selector` (0.1.16):

```
ERROR in ./node_modules/react-dropzone/dist/es/index.js
Module not found: Error: Can't resolve 'file-selector' in '/home/daniel/Development/sulu/sulu/node_modules/react-dropzone/dist/es'
 @ ./node_modules/react-dropzone/dist/es/index.js 30:0-42 378:61-70
 @ ./src/Sulu/Bundle/MediaBundle/Resources/js/components/SingleMediaDropzone/SingleMediaDropzone.js
 @ ./src/Sulu/Bundle/MediaBundle/Resources/js/components/SingleMediaDropzone/index.js
 @ ./src/Sulu/Bundle/MediaBundle/Resources/js/containers/SingleMediaUpload/SingleMediaUpload.js
 @ ./src/Sulu/Bundle/MediaBundle/Resources/js/containers/SingleMediaUpload/index.js
 @ ./src/Sulu/Bundle/MediaBundle/Resources/js/containers/Form/fields/SingleMediaUpload.js
 @ ./src/Sulu/Bundle/MediaBundle/Resources/js/containers/Form/index.js
 @ ./src/Sulu/Bundle/MediaBundle/Resources/js/index.js
 @ ./index.js                                     
 @ multi ./index.js
```

After downgrading to `file-selector` 0.1.13 the build is working again.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Make sure version 0.1.16 is installed
2. Build your application using webpack
3. See the error from above

**What is the expected behavior?**

The build should still be working.

**Comment by thecodejack** [comment]
same here

**Comment by olefirenko** [comment]
Experiencing the same issue.

**Comment by PeterPanen** [comment]
Same issue here

**Comment by thecodejack** [comment]
also there is weird Semantic version behavior I am observing. Although `react-dropzone` has `^0.1.12` mentioned this as dependency, it is only trying to resolve to `0.1.16` not `0.2.2`.

**Comment by midudev** [comment]
@thecodejack. versions starting with `0` works differently while using `^` as it only updates the patch versions and not the minor.

`^0.1.12` will update to the latest PATCH version `0.1.x`.
`^1.1.12` will update to the latest MINOR version `1.x.x`.

**Comment by thecodejack** [comment]
@midudev wow...I didn't realize that... thanks for letting me know...

**Comment by rolandjitsu** [comment]
Please update to `v0.2.2`.

**Comment by midudev** [comment]
@rolandjitsu is not that easy and I would advice to reconsider publishing a PATCH version over the minor version with the fix by cherry picking the commit.

Why? Because other dependencies, like `react-dropzone`, are using `^0.1.x`. 
https://github.com/react-dropzone/react-dropzone/blob/master/package.json#L94

This is making that `react-dropzone` is not working anymore for any of their users.

While they could upgrade to `0.2.2` this will make that:
- People will be required to upgrade to latest react-dropzone version (that could be a major for them).
- A manual process will be needed for react-dropzone and other packages.

If you just update the latest `0.1.x` version with a PATCH, the fix will just be automatically used in the next `npm install`.

**Comment by rolandjitsu** [comment]
@midudev true. I'll make a patch for 0.1.

**Comment by midudev** [comment]
Thank you so much @rolandjitsu 🙇‍♂️ and much appreciated for your work. 👏

**Comment by rolandjitsu** [comment]
> Thank you so much @rolandjitsu 🙇‍♂️ and much appreciated for your work. 👏

No worries, sorry for the mess. Please try again with v0.1.x and let me know if it works.

**Comment by midudev** [comment]
I can confirm it's working.

I reinstalled `react-dropzone@10.2.1` and now everything is working from my end. 👍

**Comment by danrot** [comment]
Can also confirm that it is working, thank you for fixing it so fast!
