### ISSUE TITLE
[BUG] File-selector interface error(TS2430) on electron

### ISSUE THREAD

**Issue by can019** [react-dropzone/file-selector#58]
**Describe the bug**
TS2430 on file-selector interface

**To Reproduce**

**Expected behavior**
 None
**Screenshots**

<img width="859" alt="스크린샷 2022-07-12 오후 1 50 05" src="https://user-images.githubusercontent.com/26926966/178411421-7021974c-c70a-4458-ba26-8144d0951de1.png">

```
node_modules/file-selector/dist/file.d.ts:3:18 - error TS2430: Interface 'FileWithPath' incorrectly extends interface 'File'.
  Types of property 'path' are incompatible.
    Type 'string | undefined' is not assignable to type 'string'.
      Type 'undefined' is not assignable to type 'string'.
3 export interface FileWithPath extends File {
                 ~~~~~~~~~~~~
```
**Desktop (please complete the following information):**
 - OS: [Ubuntu-latest]
 - Browser [Electron]
 - Version [0.6.0]

**Additional context**
In the meantime, I've added this setting to `tsconfig.json` to suppress this error by
```
{
  "compilerOptions": {
    "skipLibCheck": true,
    ...
}
```

However, I wrote an issue because it is a bug that needs to be solved one day.

**Comment by rolandjitsu** [comment]
@can019 is this still an issue?

**Comment by can019** [comment]
> @can019 is this still an issue?
@rolandjitsu 
I'm not currently using this library, so I'm not sure if the bug still exists, sorry.

**Comment by rolandjitsu** [comment]
@can019 ok, gonna go ahead and close the issue. If you ever use the lib again and get the same issue we can re-open it.
