### ISSUE TITLE
[BUG] Cannot Drag/drop email from Outlook on Safari

### ISSUE THREAD

**Issue by hctuan** [react-dropzone/file-selector#60]
**Describe the bug**
Dear,
In my project, I usually move email from outlook to the web.
It doesn't work when I drag an email from outlook and drop it on 'drop-zone'. But it works with this same behavior with Chrome and FF. Seem dataTransfer.files are empty on Safari.

**To Reproduce**
Just drop an email from outlook to dropzone

**Expected behavior**
Able to support drag/drop the email from outlook on safari like other browsers

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: safari
 - Version: Version 15.1

Thanks

**Comment by rolandjitsu** [comment]
@hctuan this is most likely a browser limitation or issue.
