### ISSUE TITLE
[BUG] Can't select a folder type when using file-selector

### ISSUE THREAD

**Issue by summerplaybook** [react-dropzone/file-selector#65]
**Describe the bug**
When the file-picker opens, I can't upload a folder
**To Reproduce**
just try to select a folder with the file picker

<img width="419" alt="image" src="https://user-images.githubusercontent.com/12703955/212758404-f50c85fc-b505-4525-a62c-a724a03c83be.png">

**Comment by rolandjitsu** [comment]
This is probably related to the file access API usage. The latest version of react-dropzone disables it by default, so it shouldn't be an issue now.
