### ISSUE TITLE
[ENHANCEMENT] Always populate a relativePath property

### ISSUE THREAD

**Issue by saul-prepared** [react-dropzone/file-selector#69]
**Is your feature request related to a problem? Please describe.**
I have built an app that has a file system/structure. When I drag and drop a folder I need to create the Folder, all sub folders and files. This works fine in the browser but breaks in my electron app.

**Describe the solution you'd like**
Always populate a relativePath property regardless of whether the {path} property exists or not.

**Describe alternatives you've considered**
I thought about just making it always set the path to the relative path. Although this would be okay for my use case, I don't know if other developers are dependent on knowing the absolute path in an electron app.

**Additional context**
This is really important as I have a production application that is behaving unexpectedly in the electron app. I have already made the necessary changes locally. Happy to discuss the solution with you.

**Comment by rolandjitsu** [comment]
This feature request is being addressed with https://github.com/react-dropzone/file-selector/pull/70, thanks @saul-prepared .
