### ISSUE TITLE
Different file objects returned when same file is dropped directly vs dropped via nested folder.

### ISSUE THREAD

**Issue by mishawakerman** [react-dropzone/file-selector#8]
As discussed in #7, when we drop a `.docx` file directly on a Dropzone we have no issues. When we drop a folder that contains the same `.docx` file, the file object is somehow different which results in downstream mimetype issues. The reason we believe this is an issue with `file-selector`/`react-dropzone` is that the following work around solves our problem:

before:
```
onDrop={this.handleAddFiles}
```

after:
```
onDrop={(newFiles) => {
    const modifiedFiles = newFiles.map(f => {
        const modifiedFile = new File([f], f.name, { type: f.type });
        modifiedFile.path = f.path;
        return modifiedFile;
    });
    this.handleAddFiles(modifiedFiles);
}}
```

Note: we do not have issues with all file types. For example, PDFs seem unaffected by the symptom.

**Comment by rolandjitsu** [comment]
@mishawakerman please provide and example illustrating your issue. From the description, I cannot tell what you mean my different types. I would like to see the types in both scenarios.

**Comment by rolandjitsu** [comment]
@mishawakerman I've also just tested it myself and I see no difference in the mime type for `.docx` files, whether the file is in a folder or not.

**Comment by mishawakerman** [comment]
Hi @rolandjitsu I don’t believe the issue is that the mime type is incorrect. There is something else “wrong” with the file object that is causing issues for us downstream from the dropzone. The reasons I believe it is something related to file-selector are: (1) we only have the issue when we drop a folder with a `docx` file and not when we drop a `docx` file directly and (2) the above workaround where we clone the file to a new file object fixes the issue. 

It’s a bit involved to setup a repro for you because the issue for us happens on our server where the mimetype is mysteriously returned as “application/octet-stream” and we can’t see how/where the type information has been either dropped or ignored because of some other property of the file object.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rolandjitsu** [comment]
@mishawakerman without a way to reproduce this it'll be hard to find the issue, if there is one.

How are you uploading the files?

**Comment by mishawakerman** [comment]
I agree. I’ll look to gather more information about what’s wrong with the file. We just use axios and attach the file:

```
var data = new FormData();
          data.append('foo', 'bar');
          data.append('file', document.getElementById('file').files[0]);
          var config = {
            onUploadProgress: function(progressEvent) {
              var percentCompleted = Math.round( (progressEvent.loaded * 100) / progressEvent.total );
            }
          };
          axios.put('/upload/server', data, config)
            .then(function (res) {
              output.className = 'container';
              output.innerHTML = res.data;
            })
            .catch(function (err) {
              output.className = 'container text-danger';
              output.innerHTML = err.message;
            });
```

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rolandjitsu** [comment]
@mishawakerman any progress on this? Otherwise I will close the issue.

**Comment by mishawakerman** [comment]
@rolandjitsu - I haven't revisited this since the above. We still have the logic that re-creates the file object in place but I'm happy if you want to close out this ticket and I can reopen if we get back to it.
