### ISSUE TITLE
Doesn't work in IE 11

### ISSUE THREAD

**Issue by taikn** [react-dropzone/file-selector#9]
**file-selector** is using `dataTransfer.items` property:
https://github.com/react-dropzone/file-selector/blob/1471fedaf041b4c226d55350febd32d7cbbeb72c/src/file-selector.ts#L40

which is not available in IE 11 (https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/items#Browser_compatibility)

**Comment by rolandjitsu** [comment]
I'm actually working on a fix for this. Will make a release soon.
